DO NOT MERGE: an example demonstrating a failure in rewriting
This commit modifies the proof script so that it fails with:

```
Error: Ltac call to "have (ssrhavefwdwbinders)" failed.
       The LHS of __top_assumption_
    (set_map f ({[x]} ∪ X))
matches but type classes inference fails
```

although the left hand side of the rewrite rule matches the goal.